apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Silvertea\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Silvertea\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/flask-live-crud-default: "true"
        io.kompose.service: flask-app
    spec:
      containers:
        - env:
            - name: DB_URL
              value: postgresql://postgres:postgres@flask_db:5432/postgres
          image: tlfoutz/flask_live_app:1.0.0
          name: flask-app
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
