apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Silvertea\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-app
  name: flask_app
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: flask-app
status:
  loadBalancer: {}
